services:
  auth-postgres:
    image: postgres:16
    container_name: nextmove_postgres_auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    ports:
      - "${POSTGRES_PORT_AUTH}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - nextmove-net

  trans-postgres:
    image: postgres:16
    container_name: nextmove_postgres_trans
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TRANS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TRANS}
      POSTGRES_DB: ${POSTGRES_DB_TRANS}
    ports:
      - "${POSTGRES_PORT_TRANS}:5432"
    volumes:
      - trans_postgres_data:/var/lib/postgresql/data
    networks:
      - nextmove-net

  mongodb:
    image: mongo:7
    container_name: nextmove_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nextmove-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nextmove_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - nextmove-net

networks:
  nextmove-net:

volumes:
  auth_postgres_data:
  trans_postgres_data:
  mongo_data: