version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nextmove_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextmove-net

  mongodb:
    image: mongo:7
    container_name: nextmove_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nextmove-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nextmove_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - nextmove-net

  redis:
    image: redis:7
    container_name: nextmove_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - nextmove-net

networks:
  nextmove-net:

volumes:
  postgres_data:
  mongo_data: